spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${REDINK_DATASOURCE_USERNAME}
    password: ${REDINK_DATASOURCE_PASSWORD}
    url: ${REDINK_DATASOURCE_URL}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

security:
  oauth2:
    client:
      clientId: ${REDINK_CLIENT_ID}
      clientSecret: ${REDINK_CLIENT_SECRET}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
      userInfoUri: https://api.github.com/user
    sso:
      loginPath: /authorization-code/callback

server:
  port: 80